steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '--build-arg', 'DATABASE_URL=${DATABASE_URL}',
           '--build-arg', 'DATABASE_TYPE=${DATABASE_TYPE}',
           '-t', 'gcr.io/tapeox/umami',
           '.']
    secretEnv: ['DATABASE_URL', 'DATABASE_TYPE']

availableSecrets:
  secretManager:
    - versionName: projects/824089784983/secrets/umami-postgresql-url/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/824089784983/secrets/umami-database-type/versions/latest
      env: 'DATABASE_TYPE'