steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 
           '--build-arg', 'DATABASE_URL=${_DATABASE_URL}',
           '-t', 'gcr.io/tapeox/umami',
           '.']
    secretEnv: ['DATABASE_URL']

availableSecrets:
  secretManager:
    - versionName: projects/824089784983/secrets/umami-postgresql-url/versions/latest
      env: 'DATABASE_URL'